name: beta

on:
  # pull_request_review:
    # types: [submitted]
  [push]
jobs:
  # upload needed-for-testing build
  upload_build_for_testing:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Check out current branch
        uses: actions/checkout@v3
      - name: Check if feature branch
        uses: ./.github/actions/check_if_feature_branch
      # create build and deploy beta if true
      - run: echo "Create beta release from branch ${{ steps.check_if_feature_branch.outputs.*  }}"
