name: beta

on:
  # pull_request_review:
    # types: [submitted]
  [push]
jobs:
  # upload needed-for-testing build
  upload_build_for_testing:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Check out current branch
        uses: actions/checkout@v3
      - name: Get branch name
        shell: bash
        run: |
          branch=${GITHUB_REF##*/} \
            echo $branch | cut -d "auto" -f2
            
        
