on: push

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
      - name: Login to JIRA
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find JIRA issue from branchname
        id: find_issue
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: "features/PWN-3182-testafdf"

      - name: Comment on issue
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ steps.find_issue.outputs.issue }}
          comment: "Issue ${{ steps.find_issue.outputs.issue }} is ready for testing right now"

      - name: Move issue to READY FOR TESTING
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.find_issue.outputs.issue }}
          transition: ${{ secrets.JIRA_READY_FOR_TESTING_TRANSITION_NAME }}