name: Map release version for tasks in Jira
on:
  push:
    branches:
      - 'release/*'

jobs:
  map_fix_version_to_tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          chmod +x Scripts/jiraMapVersionToTasks.sh
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|.*/||')
          Scripts/jiraMapVersionToTasks.sh $BRANCH_NAME
