name: Key app business unit test

on:
    pull_request:
        branches: [ develop ]
        paths:
            - 'Packages/KeyAppBusiness/Sources/**/*'
            - 'Packages/KeyAppBusiness/Tests/**/*'

jobs:
    build:
        runs-on: macos-12
        steps:
            - uses: actions/checkout@v3

            - name: Run unit tests
              working-directory: ./Packages/KeyAppBusiness
              run: |
                swift test --enable-code-coverage

            - uses: sersoft-gmbh/swift-coverage-action@v3.0.1
              id: coverage-files
              with:
                search-paths: |
                  ./Packages/KeyAppBusiness/.build

#            - name: Test coverage
#              uses: maxep/spm-lcov-action@0.3.1
#              with:
#                output-file: ./coverage/lcov.info

            - name: Bot comment
              uses: romeovs/lcov-reporter-action@v0.3.1
              with:
                  lcov-file: ${{fromJSON(steps.coverage-files.outputs.files)[0]}}
                  filter-changed-files: true

#    - name: Convert to standard format
#      run: |
#        xcrun llvm-cov export -format="lcov" .build/debug/KeyAppKitPackageTests.xctest/Contents/MacOS/KeyAppKitPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
#    - uses: codecov/codecov-action@v3
#      with:
#          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#          files: ./info.lcov # optional
#          flags: unittests # optional
#          name: codecov-umbrella # optional
#          fail_ci_if_error: true # optional (default = false)
#          verbose: true # optional (default = false)