name: Manually build feature test
on: 
  workflow_dispatch:
    inputs:
      with_high_priority:
        type: boolean
        description: With high priority
jobs:
  build-feature-test:
    uses: ./.github/workflows/build-feature-test.yml
    with:
      with-high-priority: ${{ inputs.with-high-priority }}
